### ISSUE TITLE
RFC: digitalocean/action-doctl v2

### ISSUE THREAD

**Issue by andrewsomething** [digitalocean/action-doctl#27]
I'm hoping to get some feedback from users of this GitHub Action.

When this was first authored, GitHub Actions was still in its beta phase. There have been many important changes to both how they are created and their user experience since that time. I am proposing breaking changes to the doctl action in order to bring its experience more inline with the how GitHub Actions now works.

## Current Approach

The current doctl action is based on a Docker image that wraps the `digitalocean/doctl` Docker image with a few conveniences using an entrypoint script. Though it is not fundamentally different than using `docker://digitalocean/doctl` directly. When it was first authored DigitalOcean did not publish official Docker images for doctl while they are now available.

The current Docker-based approach has a number or drawbacks. The syntax is different than the more native approach, using:

```
  with:
    args:
```

over the more straight forward:

```
    run:
```

More importantly, working with doctl commands that need access to the shared filesystem and environment accessible by other Actions in the same workflow step is difficult. This can be seen in the example right in our README:

```
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show k8s-cluster-name > $GITHUB_WORKSPACE/.kubeconfig
```

Rather than using doctl's `kubeconfig save` subcommand, we recommend redirecting the the output of `kubeconfig show`. This is because `save` would save the kubeconfig file in _the container's_ `~/.kube/config` rather than the shared runner.

This effects other doctl subcommands as well. Both `compute ssh` and `registry login` are difficult to use in any sane fashion under this approach. See for example https://github.com/digitalocean/action-doctl/issues/14 and https://github.com/digitalocean/action-doctl/issues/24

## Proposed Approach

I am proposing to re-write this action in JavaScript using the native [GitHub Actions Toolkit](https://github.com/actions/toolkit). Rather than running doctl subcommands, v2 would install doctl in the shared runner's PATH allowing it to be used directly. This would provide a much improved user experience.

Using this approach, the example from our README would now look like:

```
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save testing-cluster
```

This can simplify subsequent commands as the kubeconfig file is now available to them at their expected location removing workarounds specific to the current approach. For example, this:

     - name: Deploy to DigitalOcean Kubernetes
       run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig apply -f $GITHUB_WORKSPACE/config/deployment.yml

becomes:

```
     - name: Deploy to DigitalOcean Kubernetes
       run: kubectl apply -f $GITHUB_WORKSPACE/config/deployment.yml
```

Similarly, the workflow for pushing a container to a private DigitalOcean registry is now possible as the doctl command can write to `~/.docker/config.json`. E.g.

```
    - name: Login to Docker
      run: doctl registry login

    - name: Push image to registry
      run: docker push registry.digitalocean.com/user/example
```

### Backwards Compatibility

Current users may be referencing the action by specifying `digitalocean/action-doctl@master`. In order to not break existing users, I am proposing that a `v2` branch is created and made the default for the repository. User will need to explicitly opt-in but using `digitalocean/action-doctl@v2` to pick up these changes.

### Testing

A proof of concept is currently available in the `v2-experiment` branch and can be used right now on Linux, MacOS, and Windows workflows with:

```
    - name: Install doctl
      uses: digitalocean/action-doctl@v2-experiment
```

See here for a diff between the current code base and the proposal: https://github.com/digitalocean/action-doctl/compare/v2...v2-experiment
