### ISSUE TITLE
Creates a lot of personal access tokens

### ISSUE THREAD

**Issue by Ka1wa** [digitalocean/action-doctl#30]
Hi DO!

I have the following GitHub Actions Job:
```
steps:
- name: Save DigitalOcean kubeconfig
  uses: digitalocean/action-doctl@v2
  with:
    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

- name: Deploy to DigitalOcean Kubernetes
  run: |
    doctl kubernetes cluster kubeconfig save cluster-name
    cat ./k8s.yaml | gomplate | kubectl apply -f -
  env:
    TAG: ${{ github.sha }}
    NAMESPACE: development
```

It's working great so far, my gripe with it however though is that every build I do a new personal access token gets created. And if I go into the Tokens page (https://cloud.digitalocean.com/account/api/tokens) I have an endless list of tokens that I need to remove one-by-one.

Am I missing something or is this intended?
