### ISSUE TITLE
Unable to apply manifest files using doctl - connection refused 

### ISSUE THREAD

**Issue by Schachte** [digitalocean/action-doctl#34]
I want to apply my manifest files via actions yml.

```
name: deploy-manifests

on: 
  push:
    branches: master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-production
```

![image](https://user-images.githubusercontent.com/7055226/94392768-13e6e100-010e-11eb-8117-89d1bfdd4497.png)

I can't seem to pass this error. Am I missing something ? I'm logged in without issue:

```

Validating token... OK

>>> Successfully logged into doctl
```
