### ISSUE TITLE
Action will stop working Nov 16th

### ISSUE THREAD

**Issue by gersmann** [digitalocean/action-doctl#40]
```
Error: The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
>>> doctl version v1.51.0 installed to /home/runner/runner/_work/_tool/doctl/1.51.0/x64
```
Probably should udpate the octokit dependency

**Comment by andrewsomething** [comment]
Thanks for flagging this.

From https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

> Action authors who are using the toolkit should update the @actions/core package to v1.2.6 or greater to get the updated addPath and exportVariable functions.

We updated to v1.2.6 in: https://github.com/digitalocean/action-doctl/pull/35

We should tag a release with this change.

Though, if you specify `action-doctl@v2` you should have this change already as it refers to the branch, not the tag.

```
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
```
