### ISSUE TITLE
[SOLVED] `doctl registry login` creates superfluous API Tokens

### ISSUE THREAD

**Issue by tlhunter** [digitalocean/action-doctl#42]
I'm not quite sure if this is due to this action, or more of an issue with `doctl` itself. I have the following GitHub steps defined:

```yaml
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Install DigitalOcean Controller
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1
      - name: Authenticate with DigitalOcean Container Registry
        run: doctl registry login
      - name: Build and Push to DigitalOcean Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/$FOO/$BAR:latest
      - name: Logout from DigitalOcean Container Registry
        run: doctl registry logout
```

Each time this GitHub action runs, a new entry is added to the **Tokens/Keys** list is added with the name `container-registry-$FOO-$TIMESTAMP`. By now I seem to have hundreds of tokens in there. Is there a way to modify the use of this action to either not create so many tokens, or cleanup the tokens once they're no longer needed?
