### ISSUE TITLE
Setup without token for offline commands such as app spec validation

### ISSUE THREAD

**Issue by CBielstein** [digitalocean/action-doctl#67]
Hey DigitalOcean folks!

I use this action in both my continuous integration (PR) and continuous deployment (merged) workflows. For merge, I use it to trigger deployment of my App Platform app after running tests. For my pre-PR CI run, I use it to validate the app spec before merge.

This has been working really well for my own private use, but I've recently opened my repository for other contributors. Contributors are forking the repository and submitting PRs, which attempt to validate the app spec. But since actions from forks don't have access to secrets, the login is failing and I can't validate the spec.

I've played with the doctl CLI on my own machine and it appears spec validation `doctl apps spec validate` does not require authentication to run.

So what I'm wondering is if it'd be possible to modify this action (I'd be happy to submit a PR for it, if appropriate) to make the token optional. This would allow offline behaviors, such as app spec validation, to be run without exposing secrets to open source collaborators.

In my use case, this would look something like the following:

```yaml
      - name: Install doctl
        uses: digitalocean/action-doctl@v2

      - name: Validate app spec
        run: doctl apps spec validate .do/app.yaml
```
