### ISSUE TITLE
Self hosted runner: os.machine is not a function

### ISSUE THREAD

**Issue by maitrungduc1410** [digitalocean/action-doctl#76]
My action is failing without any error detail, it immediately throws `os.machine is not a function`. I'm using my own self hosted runner (Ubuntu 20.04)

Please help on this. Thanks

<img width="1189" alt="Screenshot 2023-08-28 at 5 11 19 PM" src="https://github.com/digitalocean/action-doctl/assets/16630193/9293b963-11ab-4a94-8f9c-d17459f83ce4">

**Comment by maitrungduc1410** [comment]
Found the issue, new version of `action-doctl` uses `os.machine` which is available from `node 16.18`, and my runner is running with old version of nodejs

So before setting up doctl I need to setup nodejs first, but it still doesnt' work:
```yml
- uses: actions/setup-node@v3
  with:
    node-version: "lts/*" # "16.18.0" also doesn't work
- name: Install doctl
  uses: digitalocean/action-doctl@v2
  with:
    token: ${{ secrets.MY_TOKEN }}
``` 
<img width="1199" alt="Screenshot 2023-08-28 at 5 43 41 PM" src="https://github.com/digitalocean/action-doctl/assets/16630193/308af7bd-c3e1-423e-857c-857f6d505988">

**Comment by andrewsomething** [comment]
GitHub hosted runners currently come with Node.js 18.17.1 preinstalled. 

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#language-and-runtime

What version of Node is installed on your runners? Node v16 is the oldest currently supported release upstream. It will be reaching end of life in September. 

https://nodejs.dev/en/about/releases/

**Comment by andrewsomething** [comment]
We've released v2.4.1 which switches to using `process` over `os` for backwards compatibility. 

https://github.com/digitalocean/action-doctl/releases/tag/v2.4.1

**Comment by maitrungduc1410** [comment]
thanks @andrewsomething for very quick action :).

Just to give you some more details about my case: 

I have a VM and I'm running self hosted running using Docker for easy on scaling + I need to run docker build in runner

My Docker image is this: https://github.com/myoung34/docker-github-actions-runner

This is environment of my Docker container:
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
# node -v
v10.19.0
```
As you can see, default nodejs version of the container is `v10.19.0`, which is old.

I have a React app which requires node 16 for `yarn install` (otherwise it'll failed during install)

So I've setup like this:
```yaml
- uses: actions/setup-node@v3
  with:
    node-version: "16.18.0"
- run: yarn install
```
It works fine, but just from this morning I noticed all my production actions failed:
```yaml
- uses: actions/setup-node@v3
  with:
    node-version: "16.18.0"
- run: yarn install
- name: Install doctl
  uses: digitalocean/action-doctl@v2
  with:
    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
```
It kept on showing `os.machine is not a function`. The thing is `yarn install` is able to pick up node v16 but seems it's not for `action-doctl`
