### ISSUE TITLE
Serverless deploy using this action seems to failing with INTERNAL_ERROR

### ISSUE THREAD

**Issue by iamsudip** [digitalocean/action-doctl#78]
Action file:
```
name: Deploy function to DO
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Setup serverless
        run: doctl serverless install
      
      - name: Connect to serverless
        run: doctl serverless connect

      - name: Deploy function
        run: doctl serverless deploy . --remote-build
```

<img width="1339" alt="Screenshot 2023-10-04 at 6 52 27 PM" src="https://github.com/digitalocean/action-doctl/assets/4931226/b3f96cda-68ff-44ba-ad68-e7242a381cdc">
