### ISSUE TITLE
Configuration for Dedicated Egress IP Addresses

### ISSUE THREAD

**Issue by JStuve** [digitalocean/action-doctl#84]
Is there a way to configure "Dedicated Egress IP Addresses"? 

Part of my migration process fails, causing the deployment to fail, sense the dedicated IPs don't toggle on. Without this configuration I have to re-enable the setting and rebuild the app from the web platform.

**Comment by andrewsomething** [comment]
Hi @JStuve, 

This project is for the doctl GitHub Action. It sounds like you are having a problem with a DigitalOcean service or doctl itself. Could you provide additional details about the issue you are experiencing so that we can help get this to the right people? 

If you are referring to creating or updating an app on App Platform using an app spec file, you can add the following to your spec to enable dedicated IP addresses:

```
egress:
  type: DEDICATED_IP
```

**Comment by JStuve** [comment]
I'm referring to creating and updating an app on App Platform using a spec file. I'm [following this documentation ](https://docs.digitalocean.com/products/app-platform/reference/app-spec/#yaml-file-structure), which doesn't reference `egress`, and my spec files looks like this:

```
services:
- name: test-app
  github:
    branch: main
    repo: test/app
  source_dir: /api/
  build_command: npm run build
  run_command: npm run start  
  egress:
    type: DEDICATED_IP
```

However the setting in the App under "Dedicated Egress IP Addresses" gets reset.

**Comment by JStuve** [comment]
Well, I realized the configuration needed to be outside of the service. This updated config worked for me:

```
egress:
    type: DEDICATED_IP
services:
- name: test-app
  github:
    branch: main
    repo: test/app
  source_dir: /api/
  build_command: npm run build
  run_command: npm run start  
```
