### ISSUE TITLE
Examples are out of date

### ISSUE THREAD

**Issue by Xe** [digitalocean/action-doctl#9]
The examples in the README reference the HCL syntax. This makes it hard to know what to do with the YAML syntax of GitHub actions. I tried to do the following and it didn't work:

```yaml
    - name: Configure Kubernetes
      uses: digitalocean/action-doctl@v1.3.0
      with:
        entrypoint: /usr/local/bin/doctl
        args: kubernetes cluster kubeconfig show kubermemes > $HOME/.kubeconfig
```

**Comment by andrewsomething** [comment]
Hi, I've just updated [the end-to-end example here](https://github.com/andrewsomething/example-doctl-action) to use the new YAML-syntax. You can find the new workflow at:

https://github.com/andrewsomething/example-doctl-action/blob/master/.github/workflows/workflow.yaml

The doctl specific piece is:

```
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show actions-example > $GITHUB_WORKSPACE/.kubeconfig
```

I'll be updating the example here momentarily.
